# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'

target 'DemoSwipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSwipe
  
  use_frameworks!

  pod 'SwipeCellKit'
  pod 'ChameleonFramework', '~> 2.1'
  # pod 'ChameleonFramework/Swift' # :git => github.com, :branch => 'swift5'

end
