# platform :ios, '9.0'
platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!

  # Pods for Flash Chat iOS13
  
  # cool typing
  pod 'CLTypingLabel', '~> 0.4.0'
  
  # firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  # keyboard manager
  # pod 'IQKeyboardManager'
  # pod 'IQKeyboardManagerSwift'

end
