# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'App-Login-Bluetooth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App-Login-Bluetooth
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
